import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import AuthProvider from "./context/AuthProvider";
import SignIn from "./components/SignIn";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import Widgets from "./components/Widgets";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "facebook-clone",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options)
  return (
    <html lang="en">
      <body className={inter.className}>
       
      {session ? (
        <AuthProvider session={session}>
          <Header />
        <main className="bg-gray-100 flex">
        <Sidebar />
       
          {children}
        <Widgets />
        </main>
        </AuthProvider>
      ) : (<SignIn/>)
      }
               
        </body>
    </html>
  );
}
