import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import Link from "next/link";
import AuthProvider from "./context/AuthProvider";
import SignIn from "./components/SignIn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options)
  return (
    <html lang="en">
      <body className={inter.className}>
       
      {session ? (
        <AuthProvider session={session}>
          {children}
        </AuthProvider>
      ) : (<SignIn/>)
      }
               
        </body>
    </html>
  );
}
